"use client";

interface PrintButtonProps {
  contentId: string;
  title?: string;
}

export default function PrintButton({ contentId, title = "MedScan AI Report" }: PrintButtonProps) {
  const handlePrint = () => {
    const el = document.getElementById(contentId);
    if (!el) return;

    const win = window.open("", "_blank");
    if (!win) return;

    win.document.write(`
      <html>
        <head>
          <title>${title}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 24px; color: #111; }
            h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 8px; }
            .card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin: 12px 0; }
            .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 12px; font-weight: bold; }
            .green { background: #dcfce7; color: #166534; }
            .red { background: #fee2e2; color: #991b1b; }
            .yellow { background: #fef9c3; color: #854d0e; }
            .blue { background: #dbeafe; color: #1e40af; }
            footer { margin-top: 32px; font-size: 11px; color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 8px; }
          </style>
        </head>
        <body>
          <h1>🔬 ${title}</h1>
          <p style="color:#6b7280;font-size:13px">Generated by MedScan AI — ${new Date().toLocaleString()}</p>
          ${el.innerHTML}
          <footer>⚠️ This report is for informational purposes only and is not a substitute for professional medical advice.</footer>
        </body>
      </html>
    `);
    win.document.close();
    win.focus();
    win.print();
    win.close();
  };

  return (
    <button
      onClick={handlePrint}
      className="flex items-center gap-2 px-4 py-2 bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-300 rounded-xl text-sm font-medium transition-colors"
    >
      🖨️ Print / Export PDF
    </button>
  );
}
